from django.contrib import admin
from main.models import *

# Register your models here.
admin.site.register(Articles)
admin.site.register(Departments)
admin.site.register(Projects)
admin.site.register(News)
admin.site.register(AboutBMSTU)
admin.site.register(Persons)
admin.site.register(Contacts)
admin.site.register(Banners)
admin.site.register(Phones)
admin.site.register(Emails)
admin.site.register(Addresses)
admin.site.register(Units)
admin.site.register(Publication)
admin.site.register(decanTime)
admin.site.register(Youth_project)
admin.site.register(Partner)
admin.site.register(Didjest_theme)
admin.site.register(Didjest_year)
admin.site.register(Didjest)
admin.site.register(About_Decan)
admin.site.register(Decan_text)
